name: Deploy Identigo Docs
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Build and deploy"
        shell: bash
        run: |
          brew install doctave/doctave/doctave
          doctave build --release --allow-failed-checks

      - name: GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: site/
        env:
          GITHUB_TOKEN: ${ { secrets.GITHUB_TOKEN } }
