name: Deploy Identigo Docs
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Deploy
    runs-on: macos-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Build and deploy"
        shell: bash
        run: |
          brew install doctave/doctave/doctave
          doctave build --release --allow-failed-checks

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
